version: '3.8'

services:
  keycloak:
      image: quay.io/keycloak/keycloak:22.0.5
      container_name: keycloak
      ports:
        - "8080:8080"
      environment:
        - KEYCLOAK_ADMIN=admin
        - KEYCLOAK_ADMIN_PASSWORD=admin
      command: ["start-dev"]

  sale_db:
    image: postgres:15
    container_name: sale_database
    environment:
      POSTGRES_DB: ${POSTGRES_DB_SALE}
      POSTGRES_USER: ${POSTGRES_USER_SALE}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD_SALE}
    ports:
      - "5001:5432"
    volumes:
      - sale_db_data:/var/lib/postgresql/data

  inventory_db:
    image: postgres:15
    container_name: inventory_database
    environment:
      POSTGRES_DB: ${POSTGRES_DB_INVENTORY}
      POSTGRES_USER: ${POSTGRES_USER_INVENTORY}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD_INVENTORY}
    ports:
      - "5002:5432"
    volumes:
      - inventory_db_data:/var/lib/postgresql/data

volumes:
  inventory_db_data:
  sale_db_data:
